package net.lex.reddit.subs.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RedditSubsCategorizedAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedditSubsCategorizedAllPropertiesEquals(RedditSubsCategorized expected, RedditSubsCategorized actual) {
        assertRedditSubsCategorizedAutoGeneratedPropertiesEquals(expected, actual);
        assertRedditSubsCategorizedAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedditSubsCategorizedAllUpdatablePropertiesEquals(
        RedditSubsCategorized expected,
        RedditSubsCategorized actual
    ) {
        assertRedditSubsCategorizedUpdatableFieldsEquals(expected, actual);
        assertRedditSubsCategorizedUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedditSubsCategorizedAutoGeneratedPropertiesEquals(
        RedditSubsCategorized expected,
        RedditSubsCategorized actual
    ) {
        assertThat(expected)
            .as("Verify RedditSubsCategorized auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedditSubsCategorizedUpdatableFieldsEquals(RedditSubsCategorized expected, RedditSubsCategorized actual) {
        assertThat(expected)
            .as("Verify RedditSubsCategorized relevant properties")
            .satisfies(e -> assertThat(e.getSub()).as("check sub").isEqualTo(actual.getSub()))
            .satisfies(e -> assertThat(e.getCat()).as("check cat").isEqualTo(actual.getCat()))
            .satisfies(e -> assertThat(e.getSubcat()).as("check subcat").isEqualTo(actual.getSubcat()))
            .satisfies(e -> assertThat(e.getNiche()).as("check niche").isEqualTo(actual.getNiche()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedditSubsCategorizedUpdatableRelationshipsEquals(
        RedditSubsCategorized expected,
        RedditSubsCategorized actual
    ) {}
}
